package ModuleV;


/**
* ModuleV/VerifierPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleV.idl
* Monday, May 18, 2015 5:01:17 PM ALMT
*/

public abstract class VerifierPOA extends org.omg.PortableServer.Servant
 implements ModuleV.VerifierOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("verify", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ModuleV/Verifier/verify
       {
         String jsonApp = in.read_string ();
         String $result = null;
         $result = this.verify (jsonApp);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ModuleV/Verifier:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Verifier _this() 
  {
    return VerifierHelper.narrow(
    super._this_object());
  }

  public Verifier _this(org.omg.CORBA.ORB orb) 
  {
    return VerifierHelper.narrow(
    super._this_object(orb));
  }


} // class VerifierPOA
