package ModuleV;


/**
* ModuleV/VerifierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleV.idl
* Monday, May 18, 2015 5:01:17 PM ALMT
*/

public interface VerifierOperations 
{
  String verify (String jsonApp);
} // interface VerifierOperations
