package ModuleV;

/**
* ModuleV/VerifierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleV.idl
* Monday, May 18, 2015 5:01:17 PM ALMT
*/

public final class VerifierHolder implements org.omg.CORBA.portable.Streamable
{
  public ModuleV.Verifier value = null;

  public VerifierHolder ()
  {
  }

  public VerifierHolder (ModuleV.Verifier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModuleV.VerifierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModuleV.VerifierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModuleV.VerifierHelper.type ();
  }

}
