package ModuleV;


/**
* ModuleV/Verifier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleV.idl
* Monday, May 18, 2015 5:01:17 PM ALMT
*/

public interface Verifier extends VerifierOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Verifier
