package ModuleAck;

/**
* ModuleAck/AcknowledgerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleAck.idl
* Monday, May 18, 2015 5:01:36 PM ALMT
*/

public final class AcknowledgerHolder implements org.omg.CORBA.portable.Streamable
{
  public ModuleAck.Acknowledger value = null;

  public AcknowledgerHolder ()
  {
  }

  public AcknowledgerHolder (ModuleAck.Acknowledger initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModuleAck.AcknowledgerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModuleAck.AcknowledgerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModuleAck.AcknowledgerHelper.type ();
  }

}
