package ModuleAck;


/**
* ModuleAck/Acknowledger.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleAck.idl
* Monday, May 18, 2015 5:01:36 PM ALMT
*/

public interface Acknowledger extends AcknowledgerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Acknowledger
