package ModuleAck;


/**
* ModuleAck/AcknowledgerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleAck.idl
* Monday, May 18, 2015 5:01:36 PM ALMT
*/

public interface AcknowledgerOperations 
{
  String ackn (String jsonApp);
} // interface AcknowledgerOperations
