package ModuleAck;


/**
* ModuleAck/AcknowledgerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleAck.idl
* Monday, May 18, 2015 5:01:36 PM ALMT
*/

abstract public class AcknowledgerHelper
{
  private static String  _id = "IDL:ModuleAck/Acknowledger:1.0";

  public static void insert (org.omg.CORBA.Any a, ModuleAck.Acknowledger that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ModuleAck.Acknowledger extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ModuleAck.AcknowledgerHelper.id (), "Acknowledger");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ModuleAck.Acknowledger read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AcknowledgerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ModuleAck.Acknowledger value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ModuleAck.Acknowledger narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModuleAck.Acknowledger)
      return (ModuleAck.Acknowledger)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModuleAck._AcknowledgerStub stub = new ModuleAck._AcknowledgerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ModuleAck.Acknowledger unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ModuleAck.Acknowledger)
      return (ModuleAck.Acknowledger)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ModuleAck._AcknowledgerStub stub = new ModuleAck._AcknowledgerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
