package ModuleHR;


/**
* ModuleHR/HumanResourcesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleHR.idl
* Monday, May 18, 2015 5:01:50 PM ALMT
*/

public interface HumanResourcesOperations 
{
  String save (String jsonApp);
} // interface HumanResourcesOperations
