package ModuleHR;

/**
* ModuleHR/HumanResourcesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleHR.idl
* Monday, May 18, 2015 5:01:50 PM ALMT
*/

public final class HumanResourcesHolder implements org.omg.CORBA.portable.Streamable
{
  public ModuleHR.HumanResources value = null;

  public HumanResourcesHolder ()
  {
  }

  public HumanResourcesHolder (ModuleHR.HumanResources initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ModuleHR.HumanResourcesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ModuleHR.HumanResourcesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ModuleHR.HumanResourcesHelper.type ();
  }

}
