package ModuleHR;


/**
* ModuleHR/HumanResources.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ModuleHR.idl
* Monday, May 18, 2015 5:01:50 PM ALMT
*/

public interface HumanResources extends HumanResourcesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface HumanResources
